### ISSUE TITLE
作者你好，请问你的字体包是怎么生成的，有教程吗

### ISSUE THREAD

**Issue by Nidcoco** [wyqACoffer/DynamicWidget#1]

**Comment by wyqACoffer** [comment]
你好，请使用Glyphs 3软件，导入你的图片，然后生成字体文件，如果你身边有视觉设计人员应该会操作，或者你可以加我的VX：15927634476

**Comment by wyqACoffer** [comment]
> _No description provided._

你好，请使用Glyphs 3软件，导入你的图片，然后生成字体文件，如果你身边有视觉设计人员应该会操作，或者你可以加我的VX：15927634476
