### ISSUE TITLE
刷新间隔

### ISSUE THREAD

**Issue by zhan139666** [wyqACoffer/DynamicWidget#2]
如何控制刷新频率，我看每个数字携带一张图片，然后每秒刷新一次，有什么办法可以提高刷新率吗

**Comment by wyqACoffer** [comment]
目前我没有方案，只能做到 1 FPS

**Comment by zhan139666** [comment]
大佬有什么其他方法可以显示类似gif图片的方案吗？widget显示动图确实做的恼火；

**Comment by huanglins** [comment]
这种要加一个动画就得加一个字体，确实普适性不强啊。
https://github.com/NeverLand-LLT/WidgetFrameAnimation  这种通过 mask 可以实现，但是超过一定时间会显示不全，可以通过调整字体来实现吗

**Comment by wyqACoffer** [comment]
刚刚看到消息，第一个问题，现在可以给字体设置一个黑色像素然后代码中动态注入图片了，或许有了一定的普适性；第二个问题，我看下他的做法哈

**Comment by wyqACoffer** [comment]
> 这种要加一个动画就得加一个字体，确实普适性不强啊。 https://github.com/NeverLand-LLT/WidgetFrameAnimation 这种通过 mask 可以实现，但是超过一定时间会显示不全，可以通过调整字体来实现吗

看了一下WidgetFrameAnimation也是依赖的Text的Timer，所以还是0123456789，10位，不清楚“超过一定时间会显示不全”是指什么，能展开说说吗

**Comment by 2020zy** [comment]
我在想市面上topwidgets 里面的动画怎么实现的，看着像加载gif一样，但是本来就不能异步加载，头大，怎么可以做稍微丝滑点的动画

**Comment by huanglins** [comment]
> > 这种要加一个动画就得加一个字体，确实普适性不强啊。 https://github.com/NeverLand-LLT/WidgetFrameAnimation 这种通过 mask 可以实现，但是超过一定时间会显示不全，可以通过调整字体来实现吗
> 
> 看了一下WidgetFrameAnimation也是依赖的Text的Timer，所以还是0123456789，10位，不清楚“超过一定时间会显示不全”是指什么，能展开说说吗

使用 WidgetFrameAnimation 中的字体，确实可以做到显示任意的图片，但是大概运行了120秒左右，图片就会显示不完整，应该就是 mask 的问题。不知道能不能简单修改字体来实现效果。

**Comment by wyqACoffer** [comment]
> 我在想市面上topwidgets 里面的动画怎么实现的，看着像加载gif一样，但是本来就不能异步加载，头大，怎么可以做稍微丝滑点的动画

gif动画已补充

**Comment by wyqACoffer** [comment]
> > > 这种要加一个动画就得加一个字体，确实普适性不强啊。 https://github.com/NeverLand-LLT/WidgetFrameAnimation 这种通过 mask 可以实现，但是超过一定时间会显示不全，可以通过调整字体来实现吗
> > 
> > 
> > 看了一下WidgetFrameAnimation也是依赖的Text的Timer，所以还是0123456789，10位，不清楚“超过一定时间会显示不全”是指什么，能展开说说吗
> 
> 使用 WidgetFrameAnimation 中的字体，确实可以做到显示任意的图片，但是大概运行了120秒左右，图片就会显示不完整，应该就是 mask 的问题。不知道能不能简单修改字体来实现效果。

GIF动画已补充

**Comment by wyqACoffer** [comment]
> 大佬有什么其他方法可以显示类似gif图片的方案吗？widget显示动图确实做的恼火；

GIF动画已补充
